export const menu = [
    {
        element: "home/index",
        path: "/home",
        menuType: "C",
        id: 1,
        orderNum: 0,
        pId: 0,
        title: "首页",
        icon: "",
        perms: "",
        isFrame: 0,
        status: 1,
        keepAlive: 1,
        hidden: 1,
    },
    {
        element: "Layout",
        path: "menu",
        menuType: "M",
        id: 2,
        orderNum: 1,
        pId: 0,
        title: "菜单嵌套",
        icon: "",
        perms: "",
        isFrame: 0,
        status: 1,
        keepAlive: 1,
        hidden: 1,
    },
    {
        element: "menu/menu1/index",
        path: "/menu/menu1",
        menuType: "C",
        id: 201,
        orderNum: 0,
        pId: 2,
        title: "菜单1",
        icon: "",
        perms: "",
        isFrame: 0,
        status: 1,
        keepAlive: 1,
        hidden: 1,
    },
]